const USER_ROLES = Object.freeze({
  ADMIN: "Admin",
  MANAGER: "Manager",
  AGENT: "Agent"
});

const LEAD_STATUSES = Object.freeze({
  NEW: "NEW",
  CONTACTED: "CONTACTED",
  QUALIFIED: "QUALIFIED",
  PROPOSAL: "PROPOSAL",
  WON: "WON",
  LOST: "LOST"
});

const LEAD_SOURCES = Object.freeze({
  WEBSITE: "WEBSITE",
  REFERRAL: "REFERRAL",
  SOCIAL_MEDIA: "SOCIAL_MEDIA",
  EMAIL_CAMPAIGN: "EMAIL_CAMPAIGN",
  PHONE: "PHONE",
  RANDOM_USER_API: "RANDOM_USER_API",
  OTHER: "OTHER"
});

const ACTIVITY_ACTIONS = Object.freeze({
  LEAD_CREATED: "LEAD_CREATED",
  LEAD_UPDATED: "LEAD_UPDATED",
  LEAD_ASSIGNED: "LEAD_ASSIGNED",
  STATUS_CHANGED: "STATUS_CHANGED"
});

module.exports = {
  USER_ROLES,
  USER_ROLE_VALUES: Object.values(USER_ROLES),
  LEAD_STATUSES,
  LEAD_STATUS_VALUES: Object.values(LEAD_STATUSES),
  LEAD_SOURCES,
  LEAD_SOURCE_VALUES: Object.values(LEAD_SOURCES),
  ACTIVITY_ACTIONS,
  ACTIVITY_ACTION_VALUES: Object.values(ACTIVITY_ACTIONS),
  CLOSED_LEAD_STATUSES: [LEAD_STATUSES.WON, LEAD_STATUSES.LOST]
};

